name: test

on:
  workflow_dispatch:

jobs:
  check:
    runs-on:
      - ubuntu-latest
    name: Check domain

    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: mypchas6fans/action-check-domain@0.18
        with:
          url: >
            https://www.google.com
            https://www.amazon.com
